export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_TIME = 'UPDATE_TIME';

export const SUBMIT_NODE_SUCCESS = 'SUBMIT_NODE_SUCCESS';
export const SUBMIT_NODE_FAILURE = 'SUBMIT_NODE_FAILURE';

export const ADD_NODE_SUCCESS = 'ADD_NODE_SUCCESS';
export const ADD_NODE_FAILURE = 'ADD_NODE_FAILURE';

export const LOAD_NODES_SUCCESS = 'LOAD_NODES_SUCCESS';
export const LOAD_NODES_FAILURE = 'LOAD_NODES_FAILURE';

export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';

export const GET_STYLE_SUCCESS = 'GET_STYLE_SUCCESS';
export const SET_STYLE_SUCCESS = 'SET_STYLE_SUCCESS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const HANDLE_ERROR = 'HANDLE_ERROR';
